version: '3'
services:
  bat_api:
    image: derrike/boneappletea:latest
    restart: always
    build:
      context: .
    ports:
      - 8080:8080
    networks:
      - frontend
      - backend
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=boneappletea
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongodb-volume:/data/db
    networks:
      - backend

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - frontend
      - backend
    depends_on:
      - mongo

volumes:
  mongodb-volume:

networks:
  frontend:
  backend:
