---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  namespace: boneappletea
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
      - name: api
        image: derrike/boneappletea
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
