---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    name: api
  namespace: boneappletea
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    name: api
