version: '3.1'

services:
    api:
        image: bat-api-img
        container_name: bat-con-api
        ports:
            - 8080:8080

    website:
        image: bat-client-img
        container_name: bat-con-client
        ports:
            - 80:80

    database:
        image: mongo
        container_name: bat-con-db
        ports:
            - 27017:27017

